- name: Install RPM Fusion repositories
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: yes
    state: present

- name: Install RPM Sphere repo
  dnf:
    name: "https://raw.githubusercontent.com/rpmsphere/noarch/master/r/rpmsphere-release-32-1.noarch.rpm"
    disable_gpg_check: yes
    state: present

- name: Install rpmsphere-release
  dnf:
    name: rpmsphere-release
    state: present
