---
- name: install Foreman/ Katello with Ansible plugin
  hosts: all
  become: true

  tasks:
    - name: install yum repositories
      yum:
        name:
          - "https://yum.puppet.com/puppet6-release-el-8.noarch.rpm"
          - "https://yum.theforeman.org/releases/nightly/el8/x86_64/foreman-release.rpm"
        state: present
        disable_gpg_check: true

    - name: install foreman-installer package
      package:
        name: foreman-installer
        state: present

    - name: install Foreman with Ansible Plugin
      command:
        cmd: foreman-installer --no-colors --enable-foreman-plugin-ansible --enable-foreman-proxy-plugin-ansible --enable-foreman-plugin-remote-execution --enable-foreman-proxy-plugin-remote-execution-ssh
      register: install_out

    - name: Foreman successfully installed
      ansible.builtin.debug:
        msg: "{{ install_out.stdout_lines }}"
      when: install_out.rc == 0

