
Vagrant.configure("2") do |config|

  config.vm.define "foreman" do |foreman|
    foreman.vm.box = "generic/centos8"
    foreman.vm.hostname = "foreman"
    foreman.vm.provider "libvirt" do |p|
      p.memory = "4096"
      p.cpus = "2"
    end
    foreman.vm.provision "ansible" do |ansible|
      ansible.playbook = "../default_playbooks/play_setup.yml"
    end
    foreman.vm.provision "ansible" do |ansible|
      ansible.playbook = "play_install_foreman.yml"
    end
  end

end
