---
- name: prepare VM for Foreman installation
  hosts: all
  become: true
  vars:
    domain: foremandomain

  tasks:
    - name: Write domain in host entry of /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: 'foreman'
        line: '127.0.0.1       foreman.{{ domain }} foreman'

    - name: permit traffic in default zone for https service
      firewalld:
        service: https
        permanent: yes
        state: enabled

    - name: open port 443 
      firewalld:
        port: 443/tcp
        permanent: yes
        state: enabled

    - name: Restart service firewalld, in all cases
      service:
        name: firewalld
        state: restarted

    - name: print ip
      ansible.builtin.debug: var=ansible_all_ipv4_addresses

