---
- name: prepare VM for Foreman installation
  hosts: all
  become: true
  vars:
    domain: trollinger
    adminuser: hille
    adminuser_ssh_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbHMqI79+z7iPSUBfMyfb9OjKm/MhsnzZTtMDeARBFjWbylCi4aWxZlQTiJFzQ7fjKXJB9ubGH8mFuoIoNZJr9nmR8EIWfluJ0ILNMx8PkDzjLea6zemt+f0hH074RErTY1N4IWOloeRcQI7zIPOk+/3z6VLZdFA9Gi/yNRp+5qhDlHWfPg+oBFdWEFboSxhXGbCTTmXk9MeHtb4gJkT1ZBENTGUklX27OK+GKRN/74Io0WnUdMPNinWcXPnYOqKZ413zySmA+mAMlOkTAPd762kekG85YvZ3oDBDpWtRtVjOya6FcURkF7nOCjS+zWMVBrrQuPG7+UJP96OIi3J/zEeNbcdYrrF7RHATZ0hw65cAac9MlpnSnMAyPb0Em/0v+eS2htE+uwwxLRs0w7a1dw/NyRBhusr5xA04t26nPa+nGXb6fJV7q7dRB+9phQuODXx7NJ6nvD1DKiprrfwDqdNhdhYDr7jtMOlSHITLgkZmtvd1/gh6/TM3Mq+AE8rCszpP60LssP/7PFj/cSHyHNLmxNI54qo6dk3yqj9uIY+NsP5vDKcJwdwShCB4WF88WwSfotLkoUD8eEQFnScT9S0g7D/XcjdcBm4YZW9dCvbgrA5cj8g6KDDg92DNIKS9BzMKPwNhj/lq6Sq3/iJ/VtyiQ+7P64QiJG62RUkdFsQ== hille@smeagol

  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create sudoers users {{ adminuser }}
      user:
        name: "{{ adminuser }}"
        groups: wheel
        append: yes
        state: present
        createhome: yes 

    - name: Set authorized key for admin user
      authorized_key:
        user: "{{ adminuser }}"
        state: present
        key: "{{ adminuser_ssh_pub }}"

    - name: Write domain in host entry of /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: 'foreman'
        line: '127.0.0.1       foreman.{{ domain }} foreman'

    - name: print ip
      ansible.builtin.debug: var=ansible_all_ipv4_addresses
